### ISSUE TITLE
Main Tracking Issue

### ISSUE THREAD

**Issue by bzm3r** [bzm3r/npch#2]
- [ ] provide a breakdown of which classes/races primaries/skills/specials are coming from, when they are tapped 
- [ ] add unique skills column to CSV (Intuition for Homonculi, Gardening for Hearthoak Seed
- [ ] if Archon is selected, make the HP icon a special, glowing “Iron Heart”
- [ ] don’t make selection boxes jump around based on Human-Academic border highlighting (actually, more importantly: replace current placeholder border highlighting with some of the other border joining options discussed)
- [ ] provide hint to player about making sure to choose classes that give them some utility both in and out of combat
- [ ] add a “flavour” column to input CSV, which includes text/image-names to show as flavour
- [ ] add pictures, judiciously
